### ISSUE TITLE
Unable to change stroke color

### ISSUE THREAD

**Issue by deveshkamboj** [netplayer/crop#2]
I was trying to give the line between the points selected, a different color but "styleStroke" is not working.
Help.

**Comment by netplayer** [comment]
Did you try strokeStyle instead? And remember to clear browser cache after any Js changes.

**Comment by deveshkamboj** [comment]
Yes, I already tried clearing cache and i’m using strokeStyle already but
it isn’t working(though line.Width is working properly idk why). Searched
online it says maybe there is some problem with ctx.begin() and ctx.close()
but i’m not getting it.

**Comment by netplayer** [comment]
Actually i also didnt make to change lines color with strokeStyle . I suspect the reason lays in the fact that canvas is in globalCompositeOperation mode which actually already turns the -normally black color- line into white and cannot be overriden by higher level styling like strokeStyle for lines. I am afraid that changing the lines color is technically impossible in this case except if you use another transparent canvas on top of the one that contains the image, which will be in normal composite mode and draw lines in it. This will complicate further the solution of course because you will have to sync the two canvases for the final crop to be effective but it's a solution.

**Comment by deveshkamboj** [comment]
Okay, so according to you its impossible to change the stroke color in
this. Actually, the stroke color is coming same as the background color. If
i change bg-color to “black” stroke becomes black and so on.

And also one more question. Is it possible to display the same picture on
the left side and cropped picture on the right. Right now we are getting
cropped images on both sides.
And is there any way by which we can add a brush kind of something. So
instead of selecting all points individually I can just hover over the part
of image I want to select using brush and it gets cropped.

**Comment by netplayer** [comment]
>>Is it possible to display the same picture on
>>the left side and cropped picture on the right. Right now we are getting
>>cropped images on both sides.

Just reload the initial picture on canvas if upload is success . Add after  if (xhr.status === 200){ line: 
`ctx.drawImage(imageObj, 0, 0);            
 imageObj.src = "img.png";`

>>And is there any way by which we can add a brush kind of something. So
>>instead of selecting all points individually I can just hover over the part
>>of image I want to select using brush and it gets cropped.

For sure there is a way but it is out of the scope of the current script. Still i don't think it;s hover what you need, rather you mean dragging, like painting probably. You can always try to deploy yourself  on top of the existing solution, or you can hire me to do it ;)  as i estimate it will take quite some effort, let alone optimization and understanding the exact requirement to the detail.

**Comment by netplayer** [comment]
Have a look also [at this script here]( http://goo.gl/ZIWfHz) i think is close to what you are after

**Comment by deveshkamboj** [comment]
Thank you so very much. Tried the first solution for uploading initial
image to canvas and it worked perfectly.

And sure I know it takes a lot of time and efforts to build any
application. I will surely get to you for the help, once I decide to take
it further to next level.

Its been really a great experience learning with you. And thanks a ton for
that. Thanks for your time and your efforts.

**Comment by deveshkamboj** [comment]
How can I add an undo button functionality into this.

**Comment by netplayer** [comment]
In order to add undo functionality  i guess you have to log and save history of mousedown or whatever client interaction and reverse them on user request on a step sequence logic.  Actually it's a matter of using some kind of database, probably session vars or the HTML5 local storage, with further  implementation method depending on specific project requirements.

**Comment by deveshkamboj** [comment]
Okay i’ll try that. Thanks alot.
